defaults:
    - submitit_slurm

name: ${data.data_name}_${model.name_file}_${prompt.eval_mode}_${prompt.k_per_slot}
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 240
cpus_per_task: 8
tasks_per_node: 1
gpus_per_node: 4
nodes: 1
qos: qos_gpu-dev
constraint: a100
gres: gpu:4
account: ohd@a100
setup:
    - module purge
    - module load cpuarch/amd
    - module load pytorch-gpu/py3/2.2.0
    - export PYTHONUSERBASE=$WORK/.local_prompting
    - export HF_DATASETS_OFFLINE=1
    - export TRANSFORMERS_OFFLINE=1
    - export HF_EVALUATE_OFFLINE=1
    - export GIT_PYTHON_REFRESH=quiet
    - export HF_TOKEN=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
    - export NCCL_P2P_DISABLE=1

additional_parameters:
    hint: nomultithread
